# Generated by Django 2.2.2 on 2019-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('teacherCareer', models.IntegerField()),
                ('classHour', models.IntegerField()),
                ('tuition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_id', models.IntegerField()),
                ('residence', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile_preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSize', models.IntegerField()),
                ('teacherCareer', models.IntegerField()),
                ('tuition', models.IntegerField()),
                ('ageDistribition', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('subjectName', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('day', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
