# Generated by Django 2.2.2 on 2019-06-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classs',
            new_name='Class',
        ),
    ]
