# Generated by Django 2.2.2 on 2019-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20190608_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_description',
            name='subject',
            field=models.IntegerField(),
        ),
    ]
