# Generated by Django 2.2.2 on 2019-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20190608_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_description',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
