# Generated by Django 2.2.2 on 2019-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20190608_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academy_id', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('office_hour', models.IntegerField()),
            ],
        ),
    ]
