# Generated by Django 2.2.2 on 2019-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20190608_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='Academy_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='academy',
            name='office_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='like',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class_description',
            name='classHour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class_description',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class_description',
            name='teacherCareer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class_description',
            name='tuition',
            field=models.IntegerField(),
        ),
    ]
