# Generated by Django 2.2.2 on 2019-06-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_auto_20190608_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='academy_name',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
